name: XRot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kódu
      uses: actions/checkout@v3

    - name: Nastavení Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalace závislostí
      run: npm install

    - name: Kontrola kvality kódu (Lint)
      run: npm run lint

    - name: Spuštění Unit Testů
      run: npm test

    - name: Build aplikace (Simulace)
      run: npm run build
